### ISSUE TITLE
Min SDK 16

### ISSUE THREAD

**Issue by hakasu28** [Mordag/hitogo#3]
Hi Alexander,
this is Harri from TEF HH.
I hope you enjoy your new Ways.
But there is a Problem with your Great Lib when using Popups with older Devices (API 16):
PopupAlertParams uses Transition, which was introduced with API 19 and crashes on API < 19.
There is a Support Variant, but this is not compatible with PopupWindow,
so the easy Way is to make a SDK Check within onCreateParams:
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
   enterTransition = holder.getCustomObject(PopupAlertParamsKeys.ENTER_TRANSITION_KEY);
   exitTransition = holder.getCustomObject(PopupAlertParamsKeys.EXIT_TRANSITION_KEY);
}
I took Build.VERSION_CODES.M here since using methods for Transition has the same case.

Greets
Harri

**Comment by AlexanderEggers** [comment]
Hi Harri,

Hope everything is going well for the TEF HH project.
I fixed the bug using your suggestion. Take a look at this commit: 7b656ce4271656e78260adf8b428fe0d2f0e2f44
If you see no issues with that, I will publish a new version tomorrow.

Cheers,
Alexander

**Comment by hakasu28** [comment]
Hi Alexander,
thats exactly what I have done to test it, so I see no issues.
Thanks for the fast fix.

Cheers,
Harri

**Comment by AlexanderEggers** [comment]
Hi Harri,

I just published the new version. 
Let me know if you find something else.

Cheers,
Alexander
