### ISSUE TITLE
DialogAlert only allows two buttons (but claims to support three)

### ISSUE THREAD

**Issue by Henkoglobin** [Mordag/hitogo#6]
When adding exactly three buttons to a DialogAlertBuilder, an `InvalidParameterException` is thrown when building the dialog, because `DialogAlertImpl` (line 295) uses `>=` rather than `>` to check for maximum amount of buttons:

            if (getController().provideIsDebugState() && dialogButtonCount >= MAX_BUILDER_BUTTON_AMOUNT) {
                throw new InvalidParameterException("Dialog only supports up to three different " +
                        "builder buttons (primary, secondary and neutral)!");
            }

**Comment by AlexanderEggers** [comment]
Indeed that's a bug. I will probably fix that  next weekend.

**Comment by Henkoglobin** [comment]
I went ahead and created a PR to fix this 😊

**Comment by AlexanderEggers** [comment]
@Henkoglobin Thanks for the PR. :) Looks good, just one line you probably need to change.

**Comment by AlexanderEggers** [comment]
@Henkoglobin I merged your PR. I will publish a new version in the next days.
