### ISSUE TITLE
Showing AlertDialog without Drawable set causing a IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Flaumbing** [Mordag/hitogo#9]
Hello Alex,

this is Flemming from TEF HH Project.
I just found a bug in the `DialogAlertImpl` when showing an AlertDialog without setting a Drawable.It results in an IndexOutOfBoundsException. It´s happening in Line 137. 

``` java  
SparseArray<Drawable> drawableMap = getParams().getDrawableMap();
        if (view != null) {
            for (int i = 0; i < drawableMap.size(); i++) {
                Integer viewId = drawableMap.keyAt(i);
                Drawable drawable = drawableMap.valueAt(i);
                setDrawable(view, viewId, drawable);
            }
        } else if (textMap.size() > 0) {
            builder.setIcon(drawableMap.valueAt(0));
        }
```

I think this should look like this:

```java  SparseArray<Drawable> drawableMap = getParams().getDrawableMap();
        if (view != null) {
            for (int i = 0; i < drawableMap.size(); i++) {
                Integer viewId = drawableMap.keyAt(i);
                Drawable drawable = drawableMap.valueAt(i);
                setDrawable(view, viewId, drawable);
            }
        } else if (drawableMap.size() > 0) {
            builder.setIcon(drawableMap.valueAt(0));
        }
```

Would be great if you could fix it and release a new version of the lib.

Greetings,
Flemming

**Comment by AlexanderEggers** [comment]
Hi Flemming,
Thanks for the bug report. I had a quick look and that is indeed something I missed when I implemented this class. I will publish 1.0.3 in the next hour. I also plan to release the first "major" release in the next days. It changes the package structure and updates the library to use AndroidX instead of the legacy classes.

Greetings from down under,
Alex

**Comment by AlexanderEggers** [comment]
1.0.3 is published. Please let me know if that fixes the issue. If yes, I would focus on 1.1.0 (and AndroidX) support next.

**Comment by Flaumbing** [comment]
Hi Alex,
perfect, the issue is fixed. Working now as expected. Thanks for your quick response!

Greetings,
Flemming

**Comment by AlexanderEggers** [comment]
Great, thanks for confirming the fix. 👍
